### ISSUE TITLE
git branch assignment

### ISSUE THREAD

**Issue by PeymanMorteza** [Andrew-Ontano/coursenotes#1]
Hi @cecileane and @coraallencoleman,

Here is the link to the network view,
https://github.com/Andrew-Ontano/coursenotes/network

Best, 

Peyman Morteza and Andrew Ontano

**Comment by cecileane** [comment]
cool! It looks like the last merge was from master into branch A, and not the other way around. If you wanted to have the last changes show in "master", you would need to checkout the master branch, and do another merge  to bring the commits from branch A into master: "git merge branchA". just fyi.
